name: Build docker images
on:
  repository_dispatch:
    types:
      - base-image-update
  push:
    paths:
      - "version.txt"
      - "dockerfile"
jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: pwsh_version
        run: |
          echo "version=$(cat version.txt | tr -d 'v')" >> $GITHUB_OUTPUT
          echo "install_version=$(cat version.txt | tr -d 'v' | cut -d '.' -f 1)" >> $GITHUB_OUTPUT

      - name: Powershell version
        run: echo ${{ steps.pwsh_version.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          build-args: |
            PWSH_VERSION=${{ steps.pwsh_version.outputs.version }}
            PWSH_INSTALL_VERSION=${{ steps.pwsh_version.outputs.install_version}}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/powershell-core:latest
            ${{ secrets.DOCKER_USERNAME }}/powershell-core:${{ steps.pwsh_version.outputs.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/powershell-core:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/powershell-core:buildcache,mode=max

      - name: Send telegram notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🖊 ${{ github.actor }} created commit:
            📩 Commit message: ${{ github.event.commits[0].message }}  

            🔧 Build status:  ${{ steps.docker_build.outcome }}

            📚 Repository: [ ${{ github.repository }} ](https://github.com/${{ github.repository }})
            📦 Image digest: ```${{ steps.docker_build.outputs.digest }}```

            🐳 See new image on [Docker hub](https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/powershell-core/tags)
